### PR TITLE
Create paddle CRD & replicas

### PR DESCRIPTION
**Pull request by jinminhao**
1. Use kubebuilder with domain: paddlepaddle.org, group: elasticserving, kind: Paddle to design and implement APIs.
2. Create CRD for paddle.
3. In PaddleSpec, define Replicas *int32 `json:"replicas,omitempty"`, 
    in PaddleStatus, define Replicas int32 `json:"replicas,omitempty"` 
    and add // +kubebuilder:subresource:status, //+kubebuilder:subresource:scale:specpath=.spec.replicas,statuspath=.status.replicas 
    for subresources status & scale.

### CODE REVIEW

**Comment by jinminhao** [comment]
1. Add controller logic for replicas. Replicas will be set to 1 if it is not set in yaml file.
2. Change pod name as paddleServing and add pod image

**Comment by jinminhao** [comment]
1. Fix the bug for the runtime error related to the function Recorder.eventf()

**Review by tizhou86 — APPROVED** [review]
/lgtm

**Pull request merged**
